server.port: 8081

spring:
  application:
    name: album-service
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root
    password: root

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

security:
  basic:
    enabled: false
---
spring:
  profiles: cloud
#eureka:
#  instance:
#    nonSecurePort: 80
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: 443
#    secureVirtualHostName: ${spring.application.name}
#    hostname: ${vcap.application.uris[0]}
#    preferIpAddress: true

security:
  oauth2:
    client:
      clientId: 9a6b5fd1d0cb72660103
      clientSecret: 926b6bf8477b76d2f204643e926b48d4a38395be
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
