---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: git-src

outputs:
- name: package-output

run:
  path: git-src/ci/tasks/package.sh

