---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

params:
  APP_DOMAIN:
  APP_HOSTNAME:

inputs:
- name: git-src

run:
  path: git-src/ci/tasks/smoke-test-java.sh
